name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v5


    - name: Install just
      uses: extractions/setup-just@v2

    - name: Run tests
      run: |
        just prcheck
